spring.application.name=git-project

# === Serveur ===
server.port=8080

# === Base de données PostgreSQL ===
spring.datasource.url=jdbc:postgresql://localhost:5432/productdb
spring.datasource.username=user
spring.datasource.password=user123
spring.datasource.driver-class-name=org.postgresql.Driver

# === JPA / Hibernate ===
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# === IA (clé chargée depuis variable d'environnement) ===
# ai.api.key=${AI_API_KEY:demo-key-not-set}
# ai.api.url=https://api.openai.com/v1/chat/completions
# ai.model=gpt-3.5-turbo
# ai.mock.enabled=false